#! /bin/sh
sxhkd &
compton -cb --config ~/.dots/misc/compton.conf &
~/.fehbg &
conky -c ~/.dots/misc/conkyrc &
~/.dots/bar/panel &
fcitx-autostart &
xrdb -merge ~/.dots/misc/Xresources
xsetroot -cursor_name left_ptr
export _JAVA_AWT_WM_NONREPARENTING=1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
